In [182]:
import pandas as pd
import numpy as np
import sklearn as sk
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
# 3.2.2

n = 5

for i in range (0,n):
    print(end='\n')
    for j in range(0,i):
        print('*', end='')



*
**
***
****

In [13]:
# 3.2.3

a = 'extra'
b = a.replace('x', '??')

b

'e??tra'

In [15]:
# 3.2.4

a = 'afbabgab'
counter = 0
for i in range(len(a)):
    if a[i] == 'a':
        for j in range(i, len(a)):
            if a[j] == 'b':
                counter += 1
counter

6

In [20]:
# 3.2.5

n = 5
a = b = 1

for i in range(2,n+1):
    a, b = b, a+b
    print(b)

2
3
5
8


In [67]:
# 4.2.2

def almost_double_factorial(n):
    a = 1
    if n>0 and n<=100:
        for i in range (1, n+1, 2):
            a *= i
        return a
    else:
        return 1
   
almost_double_factorial(102)

1

In [68]:
# 5.2.2

class MyNum:
    def __init__(self, num):
        self.num = num
    
    def get_val(self):
        return self.num
    

In [71]:
# 6.2.1 линейная алгебра

a = np.array([-5,6])
b = np.array([6,5])

np.dot(a,b)

0

In [80]:
# 7.2.5

import numpy as np

def cumulative_mean(X):
    cumsum = np.cumsum(X)
    k = np.arange(1, len(X)+1, 1)
    result = cumsum / k
    return result

#cumulative_mean([1,2,3])

cumulative_mean([1,2,3])

array([1. , 1.5, 2. ])

In [88]:
# 7.2.6

import numpy as np

def cumulative_mean_2d(X):
    cumsum = np.cumsum(X)
    k = np.arange(1, len(X)+1, 1)
    result = X
    result[0], result[1] = (cumsum[0] / k), (cumsum[1] / k)
    return result

X2d = [[1,2,3], [4,5,6]]

cumulative_mean_2d(X2d)



[array([1. , 0.5]), array([3. , 1.5])]

In [92]:
# 7.2.7

X = np.array([3, 1, 4, -1, 2, 3, 0])

def transform(X):
    Y = X
    for i in range(len(X)):
        if i%2 == 0:
            Y[i] = X[i]**3
        else:
            Y[i] = 1
    return Y

transform(X)

array([27,  1, 64,  1,  8,  1,  0])

In [113]:
# 7.2.8

X = np.array([1,2,2,4,4,6,7,8,8]).reshape(3,3)

def diag_2k(X):
    res = 0
    null = 0
    Y = X.diagonal()
    for item in Y:
        if item%2 == 0:
           res += item
        else:
            null += 1
    if null<len(Y):
        return res
    else:
        return 0

diag_2k(X)

12

In [122]:
# 8.2.2

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

def no_numpy_scalar(v1, v2):
    res = float()
    for i in range(len(v1)):
        res += v1[i]*v2[i]
    return res

def numpy_scalar(v1, v2):
    return np.dot(v1, v2)

no_numpy_scalar(v1, v2)

32.0

In [184]:
# 8.2.3

'''
m1 = 1  3  5
     2  4  6
     
m2 = 11 14
     12 15
     13 16
'''

msq1 = [[1,2], [3,4], [5,6]]
msq2 = [[11,12,13], [14,15,16]]

m1 = [[1,2], [3,4]]
m2 = [[11,12], [13,14]]

# функция ручного перемножения произвольных матриц с проверкой условия перемножения
def no_numpy_mult_all(first, second):    
    
    result = [[0 for i in range(len(first))] for i in range(len(first))]
    a = int()
    
    if len(first) == len(second[0]) and len(first[0])==len(second):
        for i in range(len(first)):
            for j in range(len(second[0])):
                for k in range(len(second)):
                    result[i][j] += first[i][k]*second[k][j]
        return result   
    else:
        print('not equal sizes')

# функция ручного перемножения квадратных матриц
def no_numpy_mult(first, second):    
    
    a = int()
    length = len(first)
    result = [[0 for i in range(length)] for i in range(length)]
    
    for i in range(length):
        for j in range(length):
            for k in range(length):
                result[i][j] += first[i][k]*second[k][j]
    return result   
    
    
def numpy_mult(first, second):
     return np.dot(first, second)

#no_numpy_mult(m1, m2)
numpy_mult(m1, m2)

array([[37, 40],
       [85, 92]])

In [185]:
# 8.2.4

def calculate_loss_function(X, w, y):              
    return (np.linalg.norm((np.dot(X, w) - y), ord=2))**2

In [187]:
# 8.2.5

# W = (X⊤ X)−1 * X⊤ * y

import numpy as np

def solve_linear_regression(X, y):
    
    XT = X.transpose()
    XTX = np.dot(XT, X)
    
    XTX_1 = np.linalg.inv(XTX)
    XT_y = np.dot(XT, y)
    w_opt = np.dot(XTX_1, XT_y)

    return w_opt


def solve_linear_regression(X, y):
    return np.dot(np.linalg.inv(np.dot(X.transpose(), X)), np.dot(X.transpose(), y))

In [192]:
# 9.2.1

x = (0-1) / 3
x = (0-2) / 3
x

-0.6666666666666666

In [194]:
# 9.2.2

a = 0
x = 0

for i in range(10,100):
    a += 1
    if (i%10 + i//10 == 5):
        x += 1
        
x/a

0.05555555555555555

In [197]:
# 9.2.3

# A U B = A + B - AB
# A = B = C = 0.5

AuB = 1/2 + 1/2 - (1/2)*(1/2)
AuBuC = 0.75 + 0.5 - 0.75*0.5
AuBuC

0.875

In [199]:
# 9.2.4

'''
8 партий
0.75 вероятность ничьи
0.125 вероятность победы
вероятность что П выиграет первым
'''

s = 0
for i in range(8):
    s += ((3/4) ** i) * (1/8)
s

0.44994354248046875

In [209]:
# 9.2.5

'''
3 присяжных
100 дел
0.3 вероятность ошибки
0.7 вероятность правильного решения

вероятность что все одновременно правы (умножение)  + вероятность что правы 2 из 3 (большинство), 
все это умножить на количество экспериментов (дел)
'''

round((0.7*0.7*0.7 + 0.3*0.7*0.7) * 100)

49

In [219]:
# 9.2.6

# набор купюр
bank = [1,2,3,4,5,6,7,8,9,10]

# количество извлекаемых купюр
k = 2

np.mean(bank) * k

11.0

In [220]:
# 9.2.7

a = [1, 2, 3, 4, 5, 6, 7]

np.std(a)

2.0

In [221]:
# 9.2.8

a = [1,3,-3,2,4,8]
b = [-2,3,0,1,3,6]

np.corrcoef(a,b)

array([[1.        , 0.82285841],
       [0.82285841, 1.        ]])

In [225]:
# 10.2.1 pandas

df = pd.DataFrame({'a': [1,2,3,4], '‘b’': [5,6,7,8], '‘c’': [9,10,11,12]}, index=[1,2,3,4])

df

a  ‘b’  ‘c’
1  1    5    9
2  2    6   10
3  3    7   11
4  4    8   12

In [227]:
# 10.2.2

ratings.rating.max()

AttributeError: 'DataFrame' object has no attribute 'rating'

In [231]:
# 10.2.3

Video_blog_DF = pd.DataFrame({'Duration': [275, 383, 628, 712],
                             'Views': [305, 629, 843, 726],
                             'Likes':[23, 78, 65, 90],
                             'Dislikes':[5, 12, 26, 10],
                             'Comments':[2, 6, 15, 28]})

Video_blog_DF.iloc[2].values

array([628, 843,  65,  26,  15])

In [276]:
# 11 pandas

df = pd.read_csv('/home/kir/Загрузки/BlackFriday.csv')
df.Age.value_counts().sort_values()

0-17      14707
55+       20903
51-55     37618
46-50     44526
18-25     97634
36-45    107499
26-35    214690
Name: Age, dtype: int64

In [286]:
df.Age.nunique()
df.query('City_Category=="A" & Gender=="M"').count()
df.query('Gender=="F" & Age=="46-50" & Purchase>20000').count()
df['Product_Category_3'].isna().sum()
(df.loc[((df['Age'] == '26-35') & (df['Gender']=='M'))].agg({'User_ID': 'count'})\
+ df.loc[((df['Age'] == '36-45') & (df['Gender']=='F'))].agg({'User_ID': 'count'})\
+ df.loc[((df['Age'] == '46-50') & (df['Gender']=='F'))].agg({'User_ID': 'count'})\
+ df.loc[((df['Age'] == '51-55') & (df['Gender']=='F'))].agg({'User_ID': 'count'})\
+ df.loc[((df['Age'] == '55+') & (df['Gender']=='F'))].agg({'User_ID': 'count'}))\
/ df['User_ID'].count()

User_ID    0.40772
dtype: float64

In [291]:
# 12 machine learning

from sklearn import metrics

y_true = [1, 0, 0, 1, 1, 1, 0, 0, 0, 1]
y_pred = [1, 1, 1, 0, 1, 1, 1, 0, 0, 1]
metrics.accuracy_score(y_true, y_pred)

y_true = [25, 60, 32, 16, 21]
y_pred = [30, 59, 36, 22, 22]
metrics.mean_squared_error(y_true, y_pred)

15.8

In [292]:
# 13 machine learning pipeline

df = pd.read_csv('/home/kir/Загрузки/forest_dataset.csv')
df.head()

0    1   2    3   4     5    6    7    8     9  ...  45  46  47  48  49  \
0  2683  333  35   30  26  2743  121  173  179  6572  ...   0   0   0   0   0   
1  2915   90   8  216  11  4433  232  228  129  4019  ...   0   0   0   0   0   
2  2941  162   7  698  76  2783  227  242  148  1784  ...   0   0   0   0   0   
3  3096   60  17  170   3  3303  231  202   99  5370  ...   0   0   0   0   0   
4  2999   66   8  488  37  1532  228  225  131  2290  ...   0   0   0   0   0   

   50  51  52  53  54  
0   0   0   0   0   2  
1   0   0   0   0   1  
2   0   0   0   0   2  
3   0   0   0   0   1  
4   0   0   0   0   2  

[5 rows x 55 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# отделить метки класса и признаки
labels = df[df.columns[-1]].values
feature_matrix = df[df.columns[:-1]].values

# разбить на обучающую и тестовую
train_feature_matrix, test_feature_matrix, train_labels, test_labels = train_test_split(
    feature_matrix, labels, test_size=0.5, random_state=0)

# создаем модель лог. регрессии
clf = LogisticRegression(C=1)
clf.fit(train_feature_matrix, train_labels)
y_pred = clf.predict(test_feature_matrix)

# считаем качество модели
accuracy_score(test_labels, y_pred)

# создаем новую модель с другим решателем сага норен полиция мальмё
clf = LogisticRegression(solver='saga')

# опишем сетку параметров
param_grid = {
    'C': np.arange(1,5),
    'penalty': ['l1', 'l2']
}

# создаем модель подбора лучших параметров
search = GridSearchCV(clf, param_grid, n_jobs=-1, cv=5, refit=True, scoring='accuracy')
search.fit(feature_matrix, labels)
search.best_params_

In [307]:
# создаем модель k-ближайших соседей

from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()
clf.fit(train_feature_matrix, train_labels)
y_pred = clf.predict(test_feature_matrix)

# считаем качество модели
accuracy_score(test_labels, y_pred)

0.7082

In [ ]:
# подберем оптимальные параметры для модели

# опишем сетку параметров
param_grid = {
    'n_neighbors': np.arange(1,10),
    'metric': ['manhattan', 'euclidean'],
    'weights': ['uniform', 'distance']
}

# создаем модель подбора лучших параметров
search = GridSearchCV(clf, param_grid, n_jobs=-1, cv=5, scoring='accuracy')
search.fit(feature_matrix, labels)
search.best_params_

In [310]:
# оценить вероятность отнесения к тому или иному классу, посчитать среднее для каждого класса

search.predict_proba(train_feature_matrix).mean(axis=0)

array([0.3676, 0.4862, 0.062 , 0.0052, 0.0156, 0.0336, 0.0298])

In [312]:
# 14 linear regression


df = pd.read_csv('/home/kir/Загрузки/penguins.csv')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [358]:
X = [[2,3,4], [5,6,7]]
y = [8,9,10]

X = np.array(X)

#X = np.insert(X, 0, np.full(len(X[0]), 1))

X = np.insert(X, 0, np.ones(len(X[0])))
X

array([1, 1, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

'''
X = 2 5
    3 6
    4 7
    
y = 8
    9
    10
'''

X = [[2,3,4], [5,6,7]]
y = [8,9,10]

class MyLinearRegression:
    def __init__(self):

        self.coef_ = None
        self.intercept_ = None

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        
        # k = (XT X)-1 XT Y
        XT = X.transpose()
        XTX = np.dot(XT, X)

        XTX_1 = np.linalg.inv(XTX)
        XT_y = np.dot(XT, y)
        w_opt = np.dot(XTX_1, XT_y)

        self.coef_ = 
        # коэффициент — свободный член.
        self.intercept_ = 

    def predict(self, X):
        pass #Можно оставить пустым